#spring
server:
  port: 8084

spring:
  application:
    name: bankacc.cmd.api
  #mongodb
  data:
    mongodb:
      host: mongo-container
      port: 27017
      database: bank-account-tracking-tokens

custom:
  axon:
    eventstore:
      database: bank-account-write
  
#axon
axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  
#security
security:
  oauth2:
    authenticationserver:
      issuer: http://api-user-auth:8083