version: '3.7'

services:
  api-user-auth:
    container_name: api-user-auth
    image: eduardorasgadoruiz/api.user.auth:1.0.0
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 8083
        published: 8083
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  api-user-command:
    container_name: api-user-command
    image: api.user.cmd:latest
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  api-user-query:
    container_name: api-user-query
    image: api.user.query:latest
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 8082
        published: 8082
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  api-bankaccount-command:
    container_name: api-bankaccount-command
    image: api.bankacc.cmd:latest
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 8084
        published: 8084
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  api-bankaccount-query:
    container_name: api-bankaccount-query
    image: api.bankacc.query:latest
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 8085
        published: 8085
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

  api-gateway:
    container_name: api-gateway
    image: eduardorasgadoruiz/api.gateway:1.0.0
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"

networks:
  default:
    external:
      name: springbankNet
